version: '3.7'

networks:
  frontend:
  backend:

volumes:
  dbdata:

services:
      
  mysql:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - backend

  phpfpm:
    build:
      context: ./phpfpm
    volumes:
      - ./wordpress:/usr/share/nginx/html
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    links:
      - mysql
    networks:
      - backend

  web:
    image: nginx:mainline
#    environment:
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: password
#      MYSQL_HOST: mysql
    volumes:
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - ./wordpress:/usr/share/nginx/html
    ports:
      - "8080:80"
    links:
      - phpfpm
    networks:
      - frontend
      - backend
