version: '3.8'

volumes:
    dbdata:

services:

    mysql:
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: password
