version: '3.7'

volumes:
    dbdata:

services:

    mysql:
        image: mysql:8.0.19
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: password
    phpfpm:
        build:
            context: ./phpfpm
        volumes:
            - ./wordpress:/usr/share/nginx/html
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: password
            MYSQL_HOST: mysql
        links:
            - mysql
