version: '3.8'

volumes:
    shared-volume:
    dbdata:

services:

    nfs:
        build:
            context: ./nfs
        volumes:
            - shared-volume:/usr/share/nginx/html
      
    mysql:
        image: mysql:8.3.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            TZ: Europe/Paris
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        labels:
            traefik.enable: "false"
      
    redis:
        image: redis:7-alpine
        labels:
            traefik.enable: "false"

    phpfpm:
        build:
            context: ./phpfpm
        volumes:
            - shared-volume:/usr/share/nginx/html
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_HOST: mysql
            WP_REDIS_HOST: redis
            WP_REDIS_PORT: 6379
        links:
            - mysql
            - redis
        labels:
            traefik.enable: "false"
        depends_on:
            - nfs

    web:
        image: nginx:mainline
        volumes:
            - ./nginx/config/conf.d:/etc/nginx/conf.d
            - shared-volume:/usr/share/nginx/html
        links:
            - phpfpm
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.web.rule=Host(`wp.polytech.io`)"
            - "traefik.http.routers.web.entrypoints=web"
        depends_on:
            - nfs
            - phpfpm

    traefik:
        image: traefik:v2.11
        container_name: traefik
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "8000:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        labels:
            traefik.enable: "false"
