version: '3.8'

volumes:
  shared-volume:
  dbdata:

services:
    nfs:
        build:
            context: ./nfs
        volumes:
            - shared-volume:/usr/share/nginx/html

    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: password
    phpfpm:
        build:
            context: ./phpfpm
        volumes:
            - shared-volume:/usr/share/nginx/html
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: password
            MYSQL_HOST: mysql
        links:
            - mysql

    web:
        image: nginx:mainline
        volumes:
            - ./nginx/config/conf.d:/etc/nginx/conf.d
            - shared-volume:/usr/share/nginx/html
        ports:
            - "8000:80"
        links:
            - phpfpm
