#
FROM debian:stretch

ENV DEBIAN_FRONTEND noninteractive

ADD https://packages.sury.org/php/apt.gpg /tmp/sury.gpg

RUN apt-get update \
    && apt-get -y install apt-transport-https lsb-release ca-certificates gnupg2 \
    && apt-key add /tmp/sury.gpg \
    && rm -f /tmp/sury.gpg \
    && sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php-sury.list' \
    && apt-get update \
    && apt-get -y install php7.3-common \
        php7.3-cli \
        php7.3-fpm \
        php7.3-mysql \
        php7.3-apcu \
        php7.3-gd \
        php7.3-imagick \
        php7.3-curl \
        php7.3-intl \
        net-tools \
        mysql-client \
    && apt-get clean \
    && apt-get autoclean

# ADD config/phpfpm.ini /etc/php5/fpm/conf.d/
RUN echo "date.timezone = Europe/Paris" > /etc/php/7.3/fpm/conf.d/20-timezone.ini
# ADD config/phpfpm.ini /etc/php5/cli/conf.d/

# tweak php-fpm config
RUN sed -i -e "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g" /etc/php/7.3/fpm/php.ini
RUN sed -i -e "s/upload_max_filesize\s*=\s*2M/upload_max_filesize = 100M/g" /etc/php/7.3/fpm/php.ini
RUN sed -i -e "s/post_max_size\s*=\s*8M/post_max_size = 100M/g" /etc/php/7.3/fpm/php.ini

# /etc/php5/fpm/php-fpm.conf
RUN sed -i -e "s/;daemonize\s*=\s*yes/daemonize = no/g" /etc/php/7.3/fpm/php-fpm.conf

# PHP FPM POOL
# RUN rm /etc/php/7.3/fpm/pool.d/www.conf
RUN sed -i -e "s/;catch_workers_output\s*=\s*yes/catch_workers_output = yes/g" /etc/php/7.3/fpm/pool.d/www.conf
RUN sed -i -e "s/pm.max_children = 5/pm.max_children = 9/g" /etc/php/7.3/fpm/pool.d/www.conf
RUN sed -i -e "s/pm.start_servers = 2/pm.start_servers = 3/g" /etc/php/7.3/fpm/pool.d/www.conf
RUN sed -i -e "s/pm.min_spare_servers = 1/pm.min_spare_servers = 2/g" /etc/php/7.3/fpm/pool.d/www.conf
RUN sed -i -e "s/pm.max_spare_servers = 3/pm.max_spare_servers = 4/g" /etc/php/7.3/fpm/pool.d/www.conf
RUN sed -i -e "s/pm.max_requests = 500/pm.max_requests = 200/g" /etc/php/7.3/fpm/pool.d/www.conf

# fix ownership of sock file for php-fpm
RUN sed -i -e "s/;listen.mode = 0660/listen.mode = 0750/g" /etc/php/7.3/fpm/pool.d/www.conf
RUN find /etc/php/7.3/cli/conf.d/ -name "*.ini" -exec sed -i -re 's/^(\s*)#(.*)/\1;\2/g' {} \;

RUN mkdir /var/run/php

VOLUME /usr/share/nginx/html

EXPOSE 9000

CMD ["php-fpm7.3", "--nodaemonize"]
