FROM debian:buster-slim

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update

# To complete
# [ ... ]

RUN mkdir /var/run/php

# To complete
# [ ... ]
VOLUME [...]

EXPOSE [...]

CMD ["/usr/sbin/php7.3-fpm", "--nodaemonize"]
